Add the ability to skip audit log update
Islandora/islandora_checksum_checker pull request #54
Opened 2019-12-20 20:48 UTC by DonRichards

**JIRA Ticket**: N/A

# What does this Pull Request do?
Turns off the modify trigger when a variable is set so that the audit log isn't triggered upon a checksum check.  

# What's new?
Looks for a variable "**islandora_checksum_checker_disable_audit_log_update**" to determine if it needs to skip the audit log trigger.

# How should this be tested?
1. Ingest a test object.
1. Run checksum checker 
1. review the audit log
1. go to drupal directory and run `$ drush vset islandora_checksum_checker_disable_audit_log_update 1`
1. Do steps #2 & #3 again to see if it had skipped the audit file update.

Verify the steps are written correctly and clearly in the README file.

# Additional Notes:
N/A

# Interested parties
@Islandora/7-x-1-x-committers

2020-01-13 15:40 UTC, mjordan commented
@DonRichards I think the 7.x workflow requires a JIRA ticket for a PR that is non-trivial but I'll drop a comment here for now. Can you create one?

I totally understand the consequences of updating the audit log (i.e., the object is considered "recently updated" and shows up in lists etc., puzzling users). In Islandora 8, fixity events are kept in a separate database so we won't have the same problem there.

But, Islandora PREMIS gets its data from the audit log. I think that if we merge this PR, we need to document on the README that if you enable this option, fixity events won't be persisted and Islandora PREMIS won't know about them. Just thought I'd point this out. If you don't care about PREMIS, this won't be a problem for you.

2020-01-14 16:00 UTC, DonRichards commented
@mjordan No problem. Here's the ticket. https://jira.lyrasis.org/browse/ISLANDORA-2497 
And I've updated the README

2020-01-16 19:48 UTC, DonRichards commented
@mjordan Any chance you had a chance to look at this?

2020-01-16 19:54 UTC, mjordan commented
Zero, but I'll get to it over the weekend at the latest.

2020-01-17 04:00 UTC, mjordan commented on README.md
> +__WARNING__: This is probably not something you want to change. That's why it isn't in the admin configuration page. Disabling this will prevent fixity checking events from being added to the audit l
s/echecksum/checksum/

2020-01-17 04:02 UTC, mjordan requested changes
@DonRichards apart from a typo in the README, this change works as intended. I toggled the new setting on and of, ran cron (which runs the checksum checker), and looked at the object's PREMIS output, which contains fixity events. Everything worked as expected.

2020-01-21 00:29 UTC, mjordan commented on README.md
> +__WARNING__: This is probably not something you want to change. That's why it isn't in the admin configuration page. Disabling this will prevent fixity checking events from being added to the audit l
@DonRichards this typo is the last thing needed before someone can merge.

2020-04-27 17:47 UTC, DonRichards commented
@mjordan any chance we could get this merged?

2020-06-19 18:15 UTC, whikloj commented
@mjordan Is this good to go?

2020-06-19 18:21 UTC, mjordan approved these changes

2020-06-19 18:21 UTC, mjordan commented
Yes, sorry, ready to merge.

2025-08-13 07:41 UTC, closed without merging